import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kirtan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>My Posts!</h1>
        <ul className={styles.posts}>
          <li>
            <p className={styles.postContent}>
              I'm working in Figma, for the first time as a designer.
            </p>
            <p className={styles.postDate}>8/12/2022</p>
          </li>
          <li>
            <p className={styles.postContent}>
              I'm working in Figma, for the first time as a designer.
            </p>
            <p className={styles.postDate}>8/12/2022</p>
          </li>
          <li>
            <p className={styles.postContent}>
              I'm working in Figma, for the first time as a designer.
            </p>
            <p className={styles.postDate}>8/12/2022</p>
          </li>
        </ul>
        <form action="">
          <textarea className={styles.inputContent}></textarea>
          <button className={styles.addButton}>Add New Post</button>
        </form>
      </main>
    </div>
  );
}
